services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.16.1
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./volumes/filebeat/logs:/var/log/server
